image(id, path, place_id)
places(id, nomplace, description, numberplace)
attendees(id, firstname, lastname, email)
eventtypes(id, eventtype)
invitations(id, event_id, attendee_id, QR_code, status)
presences(id, date_presence, heure_presence, invitation_id)
event(id, eventname, datedebut, datefin, description, place_id, eventtype_id)